on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: write
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set environment variables from .env
        uses: xom9ikk/dotenv@v2.3.0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: bufbuild/buf-action@v1
        with:
          push: false
      - run: go test -coverprofile c.out -v -race ./...