on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: write
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set environment variables from .env
        uses: xom9ikk/dotenv@v2.3.0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: bufbuild/buf-action@v1
        with:
          push: false
      - run: go test -coverprofile c.out -v -race ./...
      - name: Send results to Qlty.sh
        if: github.ref == 'refs/heads/main'
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: c.out
          strip-prefix: github.com/${{ github.repository }}/